"""Findings nobody can act on, dropped once for every rule instead of once inside each of them.

Three kinds of code answer a finding before it is made. A line ending in `//NOPMD` carries its
author's decision that the pattern is deliberate, and repeating the objection to someone who
already wrote "I know" is the fastest way to lose their attention for every other finding. A file
the SAP extension generator wrote is not code anyone chose either: it is identical in every
extension, nobody edits it, and a review of it is a review of the generator. `<Ext>Standalone.java`
and `jalo/<Ext>Manager.java` are both that second kind.

The third is a finding the review already made somewhere else. A Java method exists twice — once
where an interface declares it, once where the implementation overrides it — but changing its
signature is a single decision, and the compiler will not let half of it ship. Reporting both
halves turns one edit into two blocking findings.

Pure: findings and the changed files' content in, the same findings with some of them suppressed
out. Suppressed rather than deleted, so a lead reading the review can still see what was said and
why it was not shown.
"""

from __future__ import annotations

import re
from collections.abc import Callable

from smith.reviewer.domain.diff import lookup_by_path
from smith.reviewer.domain.models import Finding

# PMD, SonarQube and Checkstyle all take their suppression from a trailing comment, and a developer
# writes whichever one their build enforces. Which tool it names does not matter — the intent is
# the same, and it is the intent this reads.
_ACKNOWLEDGED = re.compile(r"//\s*(NOPMD|NOSONAR|CHECKSTYLE)", re.IGNORECASE)

# `<Ext>Standalone.java` is written into every extension by SAP's `extgen`, identical each time,
# and it is the shape of the template that identifies it rather than the name: a class that really
# was hand-written would not be booting the platform registry.
_GENERATED_SUFFIX = "Standalone.java"
_GENERATED_MARKER = "Registry.activateStandaloneMode()"

# `<pkg>/jalo/<Ext>Manager.java` is the other file extgen writes once per extension: the Jalo entry
# point, whose whole body is a `getInstance()` reaching into the Jalo layer to find its own
# extension. A rule telling it not to use the Jalo layer is telling it not to exist. Recognised the
# same way as the file above — the path shape plus what the body does, never the name on its own,
# because a hand-written `FooManager` outside a `jalo` package is ordinary code.
_JALO_MANAGER_PATH = re.compile(r"(?:^|/)jalo/\w+Manager\.java$")
_JALO_MANAGER_MARKER = re.compile(r"\bextends\s+Generated\w*Manager\b")

# A method declaration is a type, then the name, then the parameter list. That shape is what
# separates it from a call, where the name follows a `.` with no type in front of it — which is why
# 15 unrelated `getCurrentSession()` call sites do not read as 15 declarations of one method.
_METHOD_DECLARATION = re.compile(r"^[\w.<>\[\],\s]*\b\w[\w.<>\[\],]*\s+(\w+)\s*\(")

# `return new OrderModel(cart)` has the shape of a declaration and is a statement. The keywords
# that can precede a `(` this way are few, and none of them can open a method.
_STATEMENT_KEYWORD = re.compile(r"\b(?:return|new|throw)\b")

_OVERRIDE = re.compile(r"^\s*@Override\b")


def drop_unactionable(findings: list[Finding], files: dict[str, str]) -> list[Finding]:
    """Suppress findings whose own source says there is nothing to do about them.

    A file the review has no content for is left alone: no source is no evidence, and guessing
    from the path alone would silence real findings on a file that merely reads as generated.
    """
    sources: dict[str, list[str] | None] = {}

    def source_of(path: str) -> list[str] | None:
        if path not in sources:
            content = lookup_by_path(path, files)
            sources[path] = content.splitlines() if content is not None else None
        return sources[path]

    out: list[Finding] = []
    for finding in findings:
        lines = source_of(finding.file or "")
        if lines is None:
            out.append(finding)
        elif _is_generated(finding.file or "", lines):
            out.append(finding.suppress("generated by the SAP extension generator, not hand-written"))
        elif _is_jalo_manager(finding.file or "", lines):
            out.append(finding.suppress("the extension's Jalo entry point, which exists to reach the Jalo layer"))
        elif _is_acknowledged(lines, finding.line):
            out.append(finding.suppress("the author marked this line deliberate (NOPMD/NOSONAR)"))
        else:
            out.append(finding)
    return _drop_override_twins(out, source_of)


def _drop_override_twins(
    findings: list[Finding], source_of: Callable[[str], list[str] | None]
) -> list[Finding]:
    """Suppress an override whose interface was already reported for the same thing.

    The interface is kept because that is where the API a caller sees is declared, and so where the
    fix belongs. Runs after the suppressions above so a twin is never dropped against an interface
    finding that is itself already hidden — that would lose the decision entirely.
    """
    named = [_declared_method(source_of(f.file or ""), f.line) for f in findings]
    declaring_files: dict[tuple[str, str], set[str]] = {}
    for finding, method in zip(findings, named):
        if method is None or finding.suppressed or _overrides(source_of(finding.file or ""), finding.line):
            continue
        declaring_files.setdefault((finding.rule_id, method), set()).add(finding.file)

    out: list[Finding] = []
    for finding, method in zip(findings, named):
        elsewhere = declaring_files.get((finding.rule_id, method or ""), set()) - {finding.file}
        if (
            method is not None
            and not finding.suppressed
            and elsewhere
            and _overrides(source_of(finding.file or ""), finding.line)
        ):
            out.append(
                finding.suppress(
                    f"the same method is reported where {sorted(elsewhere)[0]} declares it, "
                    "and one signature is one decision"
                )
            )
        else:
            out.append(finding)
    return out


def _declared_method(lines: list[str] | None, line_no: int | None) -> str | None:
    """The method name a line declares, or None when the line declares no method."""
    if lines is None or line_no is None or not 1 <= line_no <= len(lines):
        return None
    match = _METHOD_DECLARATION.match(lines[line_no - 1])
    if match is None or _STATEMENT_KEYWORD.search(lines[line_no - 1][: match.start(1)]):
        return None
    return match.group(1)


def _overrides(lines: list[str] | None, line_no: int | None) -> bool:
    """Whether the declaration at `line_no` carries `@Override` on the preceding non-blank line."""
    if lines is None or line_no is None or not 1 <= line_no <= len(lines):
        return False
    for previous in reversed(lines[: line_no - 1]):
        if previous.strip():
            return _OVERRIDE.match(previous) is not None
    return False


def _is_generated(path: str, lines: list[str]) -> bool:
    return path.endswith(_GENERATED_SUFFIX) and any(_GENERATED_MARKER in line for line in lines)


def _is_jalo_manager(path: str, lines: list[str]) -> bool:
    return _JALO_MANAGER_PATH.search(path) is not None and any(
        _JALO_MANAGER_MARKER.search(line) for line in lines
    )


def _is_acknowledged(lines: list[str], line_no: int | None) -> bool:
    if line_no is None or not 1 <= line_no <= len(lines):
        return False
    return _ACKNOWLEDGED.search(lines[line_no - 1]) is not None
